app:
    resource: "@AppBundle/Controller/"
    type:     annotation

EndroidTwitterBundle:
    resource:   "@EndroidTwitterBundle/Controller/"
    type:       annotation
    prefix:     /twitterapi    